/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 EarthClouds_1_12756.glb --transform --shadows
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function EarthCloud(props) {
  const mesh2 = useRef();
  useFrame((state, delta) => {
    mesh2.current.rotation.y -= delta / 5;
  });
  const { nodes, materials } = useGLTF("/models/EarthClouds_1_12756-transformed.glb");
  return (
    <group {...props} dispose={null} ref={mesh2}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Default OBJ"]}
      />
    </group>
  );
}

useGLTF.preload("/models/EarthClouds_1_12756-transformed.glb");
