/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Hubble.glb --transform --shadows
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Hubble(props) {
  const { nodes, materials } = useGLTF("/models/Hubble-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._root.geometry}
        material={materials.transparent}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alpha_tex01.geometry}
        material={materials.NASA_logo}
        position={[0.095, 5.577, 1.454]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={0.346}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AO_1.geometry}
        material={materials.AO_1}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.257, 2.683, 2.257]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AO_light.geometry}
        material={materials.AO_light}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.257, 2.683, 2.257]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.foil_gold.geometry}
        material={nodes.foil_gold.material}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.foil_silver.geometry}
        material={materials.foil_silver}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shiny_panel.geometry}
        material={materials.shiny_panel}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={0.346}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shiny_panel_cylinder.geometry}
        material={materials.shiny_panel_cylinder}
        position={[0, -3.86, 0.724]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.257, 2.683, 2.257]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tex_01.geometry}
        material={materials.tex_01}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={0.346}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tex_02.geometry}
        material={materials.tex_02}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tex_03.geometry}
        material={materials.tex_03}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.257, 2.683, 2.257]}
      />
    </group>
  );
}

useGLTF.preload("/models/Hubble-transformed.glb");
