/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 uploads_files_3099242_lamp_3tubes.glb --transform --shadows
*/

import React, { useRef, useState } from "react";
import { useFrame } from "@react-three/fiber";
export default function SceneElement(props) {
  const mesh = useRef();
  const [size, setSize] = useState(0);
  useFrame((state, delta) => {
    // mesh.current.rotation.y -= delta / 2;
    mesh.current.rotation.z -= delta / 2;
    setSize(delta + size);
  });
  return (
    <mesh ref={mesh}>
      <planeGeometry args={[5, 5]} />
      <meshStandardMaterial wireframe />
    </mesh>
  );
}
